services:
  postgres:
    image: postgres:16-alpine
    container_name: moneymapvault-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: moneymapvault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - moneymapvault-network

  redis:
    image: redis:7-alpine
    container_name: moneymapvault-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - moneymapvault-network

volumes:
  postgres_data:
  redis_data:

networks:
  moneymapvault-network:
    driver: bridge
